### ISSUE TITLE
Namaste app not working anymore

### ISSUE THREAD

**Issue by Djang0** [garmin/connectiq-apps#19]
* Import namaste app into Eclipse ;
* Run it (whatever the watch you may select);
* Push start activity;
* you get an exception:

(null)
Unhandled Exception
UnexpectedTypeException: Expected String/Object/Array/Dictionary, given null
accelCallback in C:\Users\ludovic.reenaers\Documents\SCRIPTS\projects\connectiq-apps\apps
amaste\.\source\NamasteModel.mc:136

Windows 10
Garmin SDK 2.4.5
Eclipse IDE for Java Developers
Version: Oxygen.3a Release (4.7.3a)
Build id: 20180405-1200

That's a pitty I was about to finally succeed doing a fit contribution which I failed for weeks !!!
No Decent documentation, No decent tutorial, No functionnal App sample... I think I'm gonna give up ;(

**Comment by TravisConnectIQ** [comment]
I will look to see what is going on here and getting a fix put in place.

That said, it should be noted that the ConnectIQ SDK includes sample programs demonstrating FIT contributions. See the MoxyField and MO2Display samples. If you are stuck or just have questions, it may also be helpful to check in with the guys on the Garmin Forums (https://forums.garmin.com/forum/developers/connect-iq).

Travis

**Comment by TravisConnectIQ** [comment]
So there doesn't appear to be an actual bug here. The Namaste sample expects that the device/simulator provide accelerometer data. To do this using the simulator you must use one of the two options on the _Simulation > FIT Data_ menu. If you play back a FIT file with accelerometer data, simulate data, or run the app on a device, the app should not crash.

I can add a check to avoid the crash mentioned, or I can update the documentation in README.md. I'll talk with AlphaMonkey to see how he wants to proceed here.

**Comment by Djang0** [comment]
@TravisConnectIQ Thanks for the help. I have to admit frustration had me over reacting, sorry for that.
I tried the MoxyField, but it seemed to me that the Datafield needed some External sensor that I failed to simulate in the simulator. So I wasn't able to run tests.

I followed your advice on the namaste app, and it runs. I saved to a fit file and exported an .iq app to open the fit file in monkeygraph. But again, I failed and nothing shows up but some kind of bubbles smoking monkey ;)

My goal is to succeed in some Fitcontributions with a functioning app so that when I fail with my own app I keep in mind it is possible to succed.

Thanks again.

**Comment by TravisConnectIQ** [comment]
The instructions provided for the Namaste app, and using monkeygraph are not complete. I was able to get this all working by:

1. Run the Namaste app
2. Start simulating data (click _Simulation > FIT Data > Simulate Data_)
3. Click the start/stop button on the simulated device, and watch the timer increase
4. when the timer reaches 1 minute, click the start/stop button on the simulated device
5. Choose _Save_ from the Namaste app Resume/Save/Discard menu.
6. Wait for the progress bar to disappear. you will see an IQ! logo. this is normal.
7. Navigate to the GARMIN folder inside your temp folder
- On Windows this is %TEMP%\GARMIN
- On MacOS and Linux, look at $TMPDIR/GARMIN
8. Copy/move the appropriate .fit file to your desktop. The filenames are timestamps, so it should be pretty easy to identify the one you want.
9. From Eclipse, export the Namaste app by clicking _Connect IQ > Export Wizard_ and doing the build. Save the Namaste.iq file to the desktop.
10. Load up _monkeygraph_. It may be helpful to run it from the command line- you can get additional debugging information you wouldn't get when running it from Eclipse.
11. Click _File > IQ File_ and load the Namaste.iq file created in step 9
12. Click _File > FIT File_ and load the .FIT file from step 8.
13. Profit.

I'll check our bug database and make sure that we have something to add some documentation about acquiring the .FIT file saved by applications and using monkeygraph.

All that said, I'm willing to bet that you could've got answers quicker by reading/posting on the forums. I strongly encourage you to go there and have a look around. You don't necessarily have to post... A lot can be picked up just by lurking.

Travis

**Comment by Djang0** [comment]
Great ! Thank you very much for your help! I finally got it to work.
I think this idea of providing a framework for customizing such well designed device as garmin's is an excellent idea. I'm convinced that a more comprehensive documentation would help it get the reputation it deserves.

Thanks again for your help. Serious things will start for my project now.
