### ISSUE TITLE
datafields, libraries, watchfaces and widgets missing

### ISSUE THREAD

**Issue by xehpuk** [garmin/connectiq-apps#21]
The directories only contain a `README.md`.

**Comment by travisvitek** [comment]
Nothing is missing. These folders were created when the repo was populated, but sample apps have ever been added to them. If there were sample apps in each of those folders, they would be mentioned in the README.md.

**Comment by xehpuk** [comment]
Maybe I'm misunderstanding, but the "What's in the Repo?" section in the global `README.md` mentions all of these app types. A clarification like "may follow in the future" would be nice.

The `README.md`s of `apps` and `audio-provider` do not mention the contained apps. Only the `README.md` of `barrels` mentions the content.

At least I've found the widget `strava-api` in `apps` (wrong directory).

**Comment by BrandonConnectIQ** [comment]
I think there's some fair criticism here. I'll fix up the readme files and move the strava widget to the correct directory.

**Comment by BrandonConnectIQ** [comment]
Okay, I think I've fixed up all the organizational inconsistencies and updated the READMEs.
