### ISSUE TITLE
What's target platform my Instinct Garmin watch ?

### ISSUE THREAD

**Issue by PmcFizz** [garmin/connectiq-apps#26]
my watch is Instinct,this is newest series.  when I want develop a watchFace for it , But I don't know select 
which target platform

**Comment by hermot** [comment]
Hi, unfortunately Instinct does not support ConnectIQ :(

**Comment by PmcFizz** [comment]
No Way。I have see the Instinct app on Garmin store

**Comment by hermot** [comment]
That is just an imitation created by a third party developer so that people with CIQ capable watches can download a face that mimicks the look of the Instinct.

**Comment by PmcFizz** [comment]
I really want to develop a watch face. what's method you know  make it ?   I think it is very cool ! 3q

**Comment by hermot** [comment]
You should start here:

http://developer.garmin.com/connect-iq/programmers-guide/

If you don’t have another watch that’s CIQ capable, you could still use the simulator to help you view the watch face you develop. All is covered in the link above.

Also please visit the CIQ forums for questions and assistance:

https://forums.garmin.com/forum/developers/connect-iq

**Comment by PmcFizz** [comment]
OK 3Q very much
