### ISSUE TITLE
Let sync data to Health Connect and google fit apps. 

### ISSUE THREAD

**Issue by martasp** [garmin/connectiq-apps#55]
Let's sync data to Health Connect and google fit apps. 

Currently, you can sync through other non-reputable data providers like Health Sync https://play.google.com/store/search?q=health+sync&c=apps&hl=en&gl=US

It would be great if Garmin supported a google fit or Health Connect app:
https://play.google.com/store/apps/details?id=com.google.android.apps.healthdata&hl=en&gl=US&pli=1

**Comment by okcoker** [comment]
Anyone know if this Is this something that is on the roadmap for Garmin? I don't want want to have to depend on third party apps just to get garmin data into the google fit/health connect.

**Comment by hagen00** [comment]
I would love this too please Garmin!

**Comment by TravisConnectIQ** [comment]
This is the wrong place for this type of request. This is the github repo for ConnectIQ sample code, and what you are asking about is a data sync enhancement for Garmin Connect.

**Comment by martasp** [comment]
@TravisConnectIQ  Thank you for your explanation. Can you explain on which repository should i raise this issue?

**Comment by TravisConnectIQ** [comment]
There is no GitHub repository for Garmin Connect. Your best bet is to post in the Garmin forums. I believe this is the most appropriate place:

  https://forums.garmin.com/apps-software/mobile-apps-web/f/garmin-connect-web
