### ISSUE TITLE
Developer environment

### ISSUE THREAD

**Issue by ghost** [garmin/connectiq-apps#6]
Whats the recommended developer environment for the Garmin SDK?

**Comment by BrandonConnectIQ** [comment]
Java SDK version 7 or higher is required, and if you plan to use Eclipse as an IDE, we currently recommend Luna. Some developers have successfully used Mars, but we have not fully vetted it with our development plug-in so cannot guarantee things will function properly.

Aside from that, we recommend either Mac or Windows (no specific version requirements, other than those required for Java 7+). We do not yet support Linux.

I have attached the readme from our recently-released 1.2.0 beta SDK, which describes the installation and set-up procedure. We should be releasing an official 1.2.0 version (likely to be called 1.2.1) very soon.

Thanks,

## 

Brandon Pierce
Software QA Specialist - Connect IQ
Garmin International
913.440.3158
